<a href="https://colab.research.google.com/github/GillalaJeevana/Jeevana_INFO5502_Spring2022/blob/main/Assignment75502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The seventh Lab-assignment (03/31/2022, 50 points in total)

The purpose of this exercise is to build several regression models based on real-world datasets. 

### Question 1 (25 points) Build a regession model to predict the change in price of the stock overtime. It can either be linear regression or non-linear regression. You can download the dataset from here: https://github.com/unt-iialab/info5502-spring2022/blob/main/datasets/portfolio_data.csv. The implementation of the LSTM on this same dataset was posted here as an reference: https://www.kaggle.com/code/faressayah/stock-market-analysis-prediction-using-lstm/notebook

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from sklearn.ensemble import RandomForestRegressor


def getProtfolioDataFrame():
  df = pd.read_csv("/content/gdrive/MyDrive/portfolio_data.csv", sep= '\t')
  return df

def createXandY(df):
  X = df.drop(['Date', 'NFLX'], axis = 1)
  y = df['NFLX']
  return (X, y)

def splitData(df):
  X,y = createXandY(df)
  xtrain, xtest, ytrain, ytest = train_test_split(X, 
                                                  y, 
                                                  test_size = 0.2, 
                                                  random_state = 0)
  return (xtrain, xtest, ytrain, ytest)

#### Linear Model #######
def LinearRegressionModel(df):
  xtrain, xtest, ytrain, ytest =  splitData(df)
  LinearModel = LinearRegression()
  LinearModel.fit(xtrain, ytrain)
  yPred = LinearModel.predict(xtest)
  return yPred

###### Non Linear Model ########
def RanDomForestModel(df):
  xtrain, xtest, ytrain, ytest =  splitData(df)
  RandomModel = RandomForestRegressor(random_state=211)
  RandomModel.fit(xtrain, ytrain)
  yPred = RandomModel.predict(xtest)
  return yPred

def RMSE(ytest, yPred):
 return np.sqrt(mean_squared_error(ytest, yPred))


def r2Score(ytest, yPred):
  return  r2_score(ytest, yPred)

In [ ]:
prot_df = getProtfolioDataFrame()

In [ ]:
prot_df

Date         AMZN         DPZ          BTC        NFLX
0      5/1/2013   248.229996   51.190983   106.250000   30.415714
1      5/2/2013   252.550003   51.987320    98.099998   30.641428
2      5/3/2013   258.049988   52.446388   112.900002   30.492857
3      5/6/2013   255.720001   53.205257   109.599998   30.098572
4      5/7/2013   257.730011   54.151505   113.199997   29.464285
...         ...          ...         ...          ...         ...
1515   5/8/2019  1917.770020  283.149994  6171.959961  364.369995
1516   5/9/2019  1899.869995  282.160004  6358.290039  362.750000
1517  5/10/2019  1889.979980  278.369995  7191.359863  361.040009
1518  5/13/2019  1822.680054  273.880005  7980.129883  345.260010
1519  5/14/2019  1840.119995  272.859985  8183.830078  345.609985

[1520 rows x 5 columns]

In [ ]:
yPred = LinearRegressionModel(prot_df)

In [ ]:
yPred

array([306.13356879,  37.87352028,  35.69166279,  54.1598643 ,
        47.61272205,  54.1824834 ,  44.3605454 ,  94.54760463,
       119.16294045, 117.17697735,  97.72661699,  52.01375651,
       135.95934043, 112.80189147, 325.08934317,  40.61807849,
       173.11674181, 316.71461404,  37.73770448,  43.01011473,
        57.55702   ,  41.13307824, 136.18528659,  57.21121749,
       108.1718446 ,  52.85354646,  80.66291498,  97.12724971,
       149.20936854,  45.8105381 ,  42.33078667, 168.52611818,
       149.28189404, 137.00814388, 311.02218506,  55.0996781 ,
       279.81745562, 179.72306086, 368.1417442 , 304.6983609 ,
       217.20472455,  56.68948395, 174.9854639 ,  44.07146627,
       369.25519593, 134.60751591, 135.68593433, 165.17461608,
       175.31757129,  66.01636646, 180.02307806,  88.60122421,
       175.02532125, 116.87631044, 124.15406268, 337.70335154,
        89.9362022 , 397.2085667 , 315.28547758, 312.25517714,
        55.77877061,  42.95927055,  85.8036273 , 388.14

In [ ]:
xtrain, xtest, ytrain, ytest = splitData(prot_df)

In [ ]:
rmse = RMSE(ytest, yPred)
print(rmse)

21.479712235055025


In [ ]:
r2_score = r2Score(ytest, yPred)
print(r2_score)

0.9597280743181571


# NON linear Model

In [ ]:
YRPred = RanDomForestModel(prot_df)

In [ ]:
rmse = RMSE(ytest, YRPred)
print(rmse)

11.106742773748609


In [ ]:
r2_score = r2Score(ytest, YRPred)
print(r2_score)

0.9892324001668802


### Question 2 (25 points) The objective of this task is to detect hate speech in tweets. For the sake of simplicity, we say a tweet contains hate speech if it has a racist or sexist sentiment associated with it. So, the task is to classify racist or sexist tweets from other tweets. Formally, given a training sample of tweets and labels, where label '1' denotes the tweet is racist/sexist and label '0' denotes the tweet is not racist/sexist, your objective is to predict the labels on the test dataset. The dataset can be downloaded here: https://github.com/unt-iialab/info5502-spring2022/tree/main/datasets/Twitter%20Sentiment%20Analysis. Please build a logistic regression model for the classification, evaluation metrics include accuracy, precision, recall, and F-1 score need to be reported. 

In [ ]:
import pandas as pd
import re
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
nltk.download('punkt')
from nltk.stem import PorterStemmer
from textblob import Word
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression


def loadData(path):
  return pd.read_csv(path)

def lowerCase(tweets_list):
  return tweets_list.apply(lambda x: " ".join(x.lower() for x in x.split()))

def removePunctuation(tweets_list):
  return tweets_list.str.replace('[^\w\s]','')

def removeSpecialCharcters(tweets_list):
  return tweets_list.apply(lambda x: ''.join(re.sub(r"[^a-zA-Z0-9]+", ' ', charctr) for charctr in x ))

def removeStopWords(tweets_list):
  stop = stopwords.words('english')
  return tweets_list.apply(lambda x: " ".join(x for x in x.split() if x not in stop))

def Tokenisation(tweets_list):
  return tweets_list.apply(lambda x: TextBlob(x).words)

def stemming(tweets_list):
  ps = PorterStemmer()
  return tweets_list.apply(lambda x: " ".join([ps.stem(word) for word in x]))

def lemmitization(tweets_list):
  return tweets_list.apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))


def splitData(df, X_features):
  Y = df['label']
  X_train, X_test, y_train, y_test = train_test_split(X_features, 
                                                      Y, 
                                                      test_size=0.2)
  return (X_train, X_test, y_train, y_test)


def LogisticModel(df, X_features):
  Y = df['label']
  X_train, X_test, y_train, y_test = train_test_split(X_features, 
                                                      Y, 
                                                      test_size=0.2)
  logModel = LogisticRegression()
  logModel = logModel.fit(X_train, y_train)
  ypred = logModel.predict(X_test)
  return ypred, logModel


def classificationReport(y_test, ypred):
  return classification_report(y_test, ypred)

def confusionMatrix(y_test, ypred):
  return confusion_matrix(y_test, ypred)
 

def getFeaturesData(df):
  X = df['cleanedtextList']
  tfModel = TfidfVectorizer(min_df = 3,
                               ngram_range=(1, 2))
  vectorModel = tfModel.fit(X)
  X_features = vectorModel.transform(X).toarray()
  return X_features


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
train_Df = loadData('/content/gdrive/MyDrive/train.csv')

In [ ]:
train_Df

id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?😍😍😍😍😍ð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow  

[31962 rows x 3 columns]

In [ ]:
cleanedtextList = train_Df['tweet']
cleanedtextList = lowerCase(cleanedtextList)
cleanedtextList = removePunctuation(cleanedtextList)
cleanedtextList = removeSpecialCharcters(cleanedtextList)
cleanedtextList = removeStopWords(cleanedtextList)
cleanedtextList = Tokenisation(cleanedtextList)
cleanedtextList = stemming(cleanedtextList)
cleanedtextList = lemmitization(cleanedtextList)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: FutureWarning: The default value of regex will change from True to False in a future version.


In [ ]:
train_Df['cleanedtextList'] = cleanedtextList

In [ ]:
train_Df

id  label                                              tweet  \
0          1      0   @user when a father is dysfunctional and is s...   
1          2      0  @user @user thanks for #lyft credit i can't us...   
2          3      0                                bihday your majesty   
3          4      0  #model   i love u take with u all the time in ...   
4          5      0             factsguide: society now    #motivation   
...      ...    ...                                                ...   
31957  31958      0  ate @user isz that youuu?😍😍😍😍😍ð...   
31958  31959      0    to see nina turner on the airwaves trying to...   
31959  31960      0  listening to sad songs on a monday morning otw...   
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...   
31961  31962      0                   thank you @user for you follow     

                                         cleanedtextList  
0      user father dysfunct selfish drag kid dysfunct...  
1      user user thank lyft credit cant use caus dont...  
2                                         bihday majesti  
3                            model love u take u time ur  
4                                factsguid societi motiv  
...                                                  ...  
31957                                 ate user isz youuu  
31958  see nina turner airwav tri wrap mantl genuin h...  
31959           listen sad song monday morn otw work sad  
31960   user sikh templ vandalis calgari wso condemn act  
31961                                  thank user follow  

[31962 rows x 4 columns]

In [ ]:
X_features = getFeaturesData(train_Df)

In [ ]:
yPred, model = LogisticModel(train_Df, X_features)

In [ ]:
X_train, X_test, y_train, y_test = splitData(train_Df, X_features)

In [ ]:
clasReport = classificationReport(y_test, yPred)

In [ ]:
clasReport

'              precision    recall  f1-score   support\n\n           0       0.93      0.98      0.95      5948\n           1       0.06      0.02      0.03       445\n\n    accuracy                           0.91      6393\n   macro avg       0.49      0.50      0.49      6393\nweighted avg       0.87      0.91      0.89      6393\n'

In [ ]:
confusionMatrix = confusionMatrix(y_test, yPred)

In [ ]:
confusionMatrix

array([[5792,  136],
       [ 451,   14]])

# Test Data

In [ ]:
test_Df = loadData('/content/gdrive/MyDrive/test.csv')

In [ ]:
test_Df

id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [ ]:
cleanedtextList = test_Df['tweet']
cleanedtextList = lowerCase(cleanedtextList)
cleanedtextList = removePunctuation(cleanedtextList)
cleanedtextList = removeSpecialCharcters(cleanedtextList)
cleanedtextList = removeStopWords(cleanedtextList)
cleanedtextList = Tokenisation(cleanedtextList)
cleanedtextList = stemming(cleanedtextList)
cleanedtextList = lemmitization(cleanedtextList)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: FutureWarning: The default value of regex will change from True to False in a future version.


In [ ]:
test_Df['cleanedtextList'] = cleanedtextList

In [ ]:
test_Df

id                                              tweet  \
0      31963  #studiolife #aislife #requires #passion #dedic...   
1      31964   @user #white #supremacists want everyone to s...   
2      31965  safe ways to heal your #acne!!    #altwaystohe...   
3      31966  is the hp and the cursed child book up for res...   
4      31967    3rd #bihday to my amazing, hilarious #nephew...   
...      ...                                                ...   
17192  49155  thought factory: left-right polarisation! #tru...   
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...   
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...   
17195  49158  happy, at work conference: right mindset leads...   
17196  49159  my   song "so glad" free download!  #shoegaze ...   

                                         cleanedtextList  
0      studiolif aislif requir passion dedic willpow ...  
1      user white supremacist want everyon see new bi...  
2              safe way heal acn altwaystoh healthi heal  
3      hp cur child book reserv alreadi ye harrypott ...  
4      3rd bihday amaz hilari nephew eli ahmir uncl d...  
...                                                  ...  
17192  thought factori leftright polaris trump uselec...  
17193  feel like mermaid hairflip neverreadi formal w...  
17194  hillari campaign today ohioomg amp use word li...  
17195  happi work confer right mindset lead cultureof...  
17196     song glad free download shoegaz newmus newsong  

[17197 rows x 3 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer(min_df = 3,
                             ngram_range=(1, 2))

In [ ]:
test_Df

id                                              tweet  \
0      31963  #studiolife #aislife #requires #passion #dedic...   
1      31964   @user #white #supremacists want everyone to s...   
2      31965  safe ways to heal your #acne!!    #altwaystohe...   
3      31966  is the hp and the cursed child book up for res...   
4      31967    3rd #bihday to my amazing, hilarious #nephew...   
...      ...                                                ...   
17192  49155  thought factory: left-right polarisation! #tru...   
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...   
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...   
17195  49158  happy, at work conference: right mindset leads...   
17196  49159  my   song "so glad" free download!  #shoegaze ...   

                                         cleanedtextList  
0      studiolif aislif requir passion dedic willpow ...  
1      user white supremacist want everyon see new bi...  
2              safe way heal acn altwaystoh healthi heal  
3      hp cur child book reserv alreadi ye harrypott ...  
4      3rd bihday amaz hilari nephew eli ahmir uncl d...  
...                                                  ...  
17192  thought factori leftright polaris trump uselec...  
17193  feel like mermaid hairflip neverreadi formal w...  
17194  hillari campaign today ohioomg amp use word li...  
17195  happi work confer right mindset lead cultureof...  
17196     song glad free download shoegaz newmus newsong  

[17197 rows x 3 columns]

In [ ]:
test_data_features = getFeaturesData(test_Df)
print(test_data_features)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
model

LogisticRegression()